import AuthenticityToken from './components/authenticityToken';
import BackgroundSelector from './components/background_selector';
import CampaignForm from './components/NewCampaignForm';
import CampaignsIndex from './components/campaignsIndex';
import CharactersIndex from './components/charactersIndex';
import CreateCharacterButton from './components/createCharacter';
import Dashboard from './components/dashboard';
import Login from './components/login';
import LoginButton from './components/sign_in';
import LoginForm from './components/login_form';
import LogoutButton from './components/logout';
import Navbar from './components/navbar';
import { Panel, PanelTitle, PanelBody } from './components/panel';
import QgenNavbar from './components/qgenNavbar';
import SelectBackground from './components/select_background';
import ShowCampaign from './components/showCampaign';
import ShowCharacter from './components/showCharacter';

window.AuthenticityToken = AuthenticityToken;
window.BackgroundSelector = BackgroundSelector;
window.CampaignForm = CampaignForm;
window.CampaignsIndex = CampaignsIndex;
window.CharactersIndex = CharactersIndex;
window.CreateCharacterButton = CreateCharacterButton;
window.Dashboard = Dashboard;
window.Login = Login;
window.LoginButton = LoginButton;
window.LoginForm = LoginForm;
window.LogoutButton = LogoutButton;
window.Navbar = Navbar;
window.Panel = Panel;
window.PanelBody = PanelBody;
window.PanelTitle = PanelTitle;
window.QgenNavbar = QgenNavbar;
window.SelectBackground = SelectBackground;
window.ShowCampaign = ShowCampaign;
window.ShowCharacter = ShowCharacter;
