import AuthenticityToken from './components/authenticityToken';
import BackgroundSelector from './components/background_selector';
import CreateCharacterButton from './components/createCharacter';
import Dashboard from './components/dashboard';
import Login from './components/login';
import LoginButton from './components/sign_in';
import LoginForm from './components/login_form';
import LogoutButton from './components/logout';
import Navbar from './components/navbar';
import Panel from './components/panel';
import PanelBody from './components/panelBody';
import PanelTitle from './components/panelTitle';
import SelectBackground from './components/select_background';

window.AuthenticityToken = AuthenticityToken;
window.BackgroundSelector = BackgroundSelector;
window.CreateCharacterButton = CreateCharacterButton;
window.Dashboard = Dashboard;
window.Login = Login;
window.LoginButton = LoginButton;
window.LoginForm = LoginForm;
window.LogoutButton = LogoutButton;
window.Navbar = Navbar;
window.Panel = Panel;
window.PanelBody = PanelBody;
window.PanelTitle = PanelTitle;
window.SelectBackground = SelectBackground;
